spring.application.name=jwt_implementation

server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/jwtinfo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=karthik@05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=suFLtEgmfHq8AYkuAHvbf2Gxj1YPamskhfAzpWBDOub